// test-system/templates/react-cra-no-sw/src/pages/Products.js
import React, { useState, useEffect } from 'react';

function Products() {
  const [products, setProducts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetch('http://localhost:18001/api/products')
      .then(response => response.json())
      .then(data => {
        setProducts(Array.isArray(data) ? data : []);
        setLoading(false);
      })
      .catch(err => {
        setError(err.message);
        setLoading(false);
      });
  }, []);

  if (loading) return <div className="page">Loading products...</div>;
  if (error) return <div className="page">Error: {error}</div>;

  return (
    <div className="page">
      <h2>Products</h2>
      <div className="products-grid">
        {products && products.length > 0 ? (
          products.map(product => (
            <div key={product.id} className="product-card">
              <h3>{product.name}</h3>
              <p>{product.description}</p>
              <p className="price">${product.price}</p>
            </div>
          ))
        ) : (
          <p>No products available.</p>
        )}
      </div>
    </div>
  );
}

export default Products;

// test-system/templates/vue3-vite-no-sw/src/pages/Products.vue
<template>
  <div class="page">
    <h2>Products</h2>
    <div v-if="loading">Loading products...</div>
    <div v-else-if="error">Error: {{ error }}</div>
    <div v-else class="products-grid">
      <div v-if="products && products.length > 0">
        <div v-for="product in products" :key="product.id" class="product-card">
          <h3>{{ product.name }}</h3>
          <p>{{ product.description }}</p>
          <p class="price">${{ product.price }}</p>
        </div>
      </div>
      <p v-else>No products available.</p>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Products',
  data() {
    return {
      products: [],
      loading: true,
      error: null
    }
  },
  mounted() {
    fetch('http://localhost:18001/api/products')
      .then(response => response.json())
      .then(data => {
        this.products = Array.isArray(data) ? data : [];
        this.loading = false;
      })
      .catch(err => {
        this.error = err.message;
        this.loading = false;
      });
  }
}
</script>
